### ISSUE TITLE
Example app gives red screen once first message is sent

### ISSUE THREAD

**Issue by jhilgedick-disney** [couchbaselabs/mobile-dart-flutter-plugin#37]
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building ChatMessageTile(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#0d566]]):
Null check operator used on a null value

The relevant error-causing widget was:
    ChatMessageTile ChatMessageTile:file:///Users/John.Hilgedick/src/mobile-dart-flutter-plugin/example/lib/main.dart:105:26

When the exception was thrown, this was the stack:
#0      CblChatMessage.message (package:example/main.dart:212:46)
main.dart:212
#1      ChatMessageTile.build (package:example/main.dart:130:30)
main.dart:130
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:5541:49)
framework.dart:5541
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
framework.dart:5471
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453:5)
framework.dart:5453
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
framework.dart:5447
...     Normal element mounting (41 frames)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
```

**Comment by Jeff-Couchbase** [comment]
@jhilgedick-disney can you please check fix on your side. thanks!
